// <auto-generated />
namespace MyCards.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changerankingstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changerankingstable));
        
        string IMigrationMetadata.Id
        {
            get { return "201604291533052_change-rankings-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
