// <auto-generated />
namespace MyCards.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixalltables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixalltables));
        
        string IMigrationMetadata.Id
        {
            get { return "201605121051357_fix-all-tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
