// <auto-generated />
namespace MyCards.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixtablegroupun : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixtablegroupun));
        
        string IMigrationMetadata.Id
        {
            get { return "201605071519438_fix-table-groupun"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
